services:

  app:
    build: .
    container_name: mytube-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    # 🔥 YEH VALA BLOCK JODIYE
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    build: .
    container_name: mytube-worker
    command: npm run worker
    env_file:
      - .env
    # 🔥 YEH VALA BLOCK BHI JODIYE
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: mytube-redis
    ports:
      - "6379:6379"